# Listen interface.
listen_addr: 0.0.0.0:8000
# Base path of Docker Registry UI.
base_path: /

# Registry URL with schema and port.
registry_url: http://localhost:5000
# Verify TLS certificate when using https.
verify_tls: false

# Docker registry credentials.
# They need to have a full access to the registry.
# If token authentication service is enabled, it will be auto-discovered and those credentials
# will be used to obtain access tokens.
# When the registry_password_file entry is used, the password can be passed as a docker secret 
# and read from file. This overides the registry_password entry.
#registry_username: user
#registry_password: pass
# registry_password_file: /run/secrets/registry_password_file

# Event listener token.
# The same one should be configured on Docker registry as Authorization Bearer token.
event_listener_token: token
# Retention of records to keep.
event_retention_days: 7

# Event listener storage.
event_database_driver: sqlite3
event_database_location: data/registry_events.db
# event_database_driver: mysql
# event_database_location: user:password@tcp(localhost:3306)/docker_events

# Cache refresh interval in minutes.
# How long to cache repository list and tag counts.
cache_refresh_interval: 10

# If users can delete tags. If set to False, then only admins listed below.
anyone_can_delete: false
# Users allowed to delete tags.
# This should be sent via X-WEBAUTH-USER header from your proxy.
admins: []

# Debug mode. Affects only templates.
debug: true

# How many days to keep tags but also keep the minimal count provided no matter how old.
purge_tags_keep_days: 90
purge_tags_keep_count: 20
# Enable built-in cron to schedule purging tags in server mode.
# Empty string disables this feature.
# Example: '25 54 17 * * *' will run it at 17:54:25 daily.
# Note, the cron schedule format includes seconds! See https://godoc.org/github.com/robfig/cron
purge_tags_schedule: ''

purge: # CAUTION: Rules (on repository AND on tags) are evaluated SEQUENTIALLY, first match win
  - repo_regex: 'myrepo/myimg$' # Keep only 5 last tags and 10 days in the /myrepo/myimg image
    tags:
    - tags_regex: '.*'
      tags_keep_days: 10
      tags_keep_count: 5
  - repo_regex: 'test/*' # Apply differents rules based on tags pattern for all images in the /test repository
    tags:
    - tags_regex: '.*-dev-.*' # Apply rule on all tags which contains '-dev-' pattern (like a branch image)
      tags_keep_days: 0
      tags_keep_count: 2
    - tags_regex: '.*' # Apply rule on all **others** tags
      tags_keep_days: 10
      tags_keep_count: 5